### ISSUE TITLE
Playground test fails if I try to add one more entity to DB

### ISSUE THREAD

**Issue by fjod** [reinforced/Reinforced.Tecture#6]
file: **Playground\Reinforced.Samples.ToyFactory.Tests\WarehouseTests\ManageTests.cs**
test: **SupplyCreationPipeline**

Test works like this:
         
```
            using var c = Case<SupplyCreationPipeline_TestData>(out ITecture ctx);
            var m = ctx.Do<Manage>();
            var unit = m.CreateMeasurementUnit("Kilograms", "kG");
            ctx.Save();
            var res1 = m.CreateResource("resource1", "kG");
            var res2 = m.CreateResource("resource2", "kG");
            var res3 = m.CreateResource("resource3", "kG");
            ctx.Save();
```

But if I try to add another resource like:
          
         
```
            var res1 = m.CreateResource("resource1", "kG");
            var res2 = m.CreateResource("resource2", "kG");
            var res3 = m.CreateResource("resource3", "kG");
            ctx.Save();
            var res4 = m.CreateResource("resource4444", "kG");
            ctx.Save();
```

or

```
           var res1 = m.CreateResource("resource1", "kG");
           var res2 = m.CreateResource("resource2", "kG");
            var res3 = m.CreateResource("resource3", "kG");        
            var res4 = m.CreateResource("resource4444", "kG");
            ctx.Save();
```

Test fails with:

```
Reinforced.Tecture.Testing.Data.QueryOrderMismatchException: Query order violation at position 0 : 'ORM Addition PK retrieval' query expected but 'check resource existence' got
   at Reinforced.Tecture.Testing.Data.CSharpTestData.Get[T](String hash, String description) in C:\study\Reinforced.Tecture\Testing\Reinforced.Tecture.Testing\Data\CSharpTestData.cs:line 114
```

I found this issue when I tried to understand how sql query is constructed from lambda. File in case **Reinforced.Samples.ToyFactory.Logic.Warehouse\Services\Supply.cs** 

method 

**public IAddition<ResourceSupply> CreateResourceSupply(string name, IEnumerable<ResourceItemDto> items)**

line: 
```
 var byIds = From<Db>().SqlQuery<Resource> //get Id's from db which are present in new supply?
                    (x => $"SELECT * FROM {x} WHERE {knownIds.Contains(x.Id)}").As<Resource>();

```
In test case there is only one resource with Id set; so I tried to add another one and it fails.

**Comment by pavel-b-novikov** [comment]
— Юнит-тест падает если я меняю логику!
— Да неужели? Хмм, действительно :)

**Comment by fjod** [comment]
I wrote another test like this:

```
            using var c = Case(out ITecture ctx);
            var m = ctx.Do<Manage>();
            var unit = m.CreateMeasurementUnit("Kilograms", "kG");
            ctx.Save();
            var res1 = m.CreateResource("resource1", "kG");
            var res2 = m.CreateResource("resource2", "kG");
            var res3 = m.CreateResource("resource3", "kG");
            var res4 = m.CreateResource("resource4", "kG");
            ctx.Save();
            Output.WriteLine(c.Text());
```

And it works pretty nice :D

**Comment by pavel-b-novikov** [comment]
Само собой, удалил валидацию и тестовые данные - и оно предсказуемо заработало :)

Посмотри в соседнюю папку - там для твоего тест новые данные/валидация сгенерились

**Comment by fjod** [comment]
Files were generated, I changed test to look like this:

```
public void Test()
        {
            using var c = Case
                <Test_TestData>
                (out ITecture ctx);
            var m = ctx.Do<Manage>();
            var unit = m.CreateMeasurementUnit("Kilograms", "kG");
            ctx.Save();
            var res1 = m.CreateResource("resource1", "kG");
            var res2 = m.CreateResource("resource2", "kG");
            var res3 = m.CreateResource("resource3", "kG");
            var res4 = m.CreateResource("resource4", "kG");
            ctx.Save();
            Output.WriteLine(c.Text());
            c.Validate<Test_Validation>();
        }
```

Now test fails with error:
```
Reinforced.Tecture.Testing.Data.QueryOrderMismatchException: Query order violation at position 0 : 'check unit existence' query expected but 'check unit existence' got
   at Reinforced.Tecture.Testing.Data.CSharpTestData.Get[T](String hash, String description) in C:\study\Reinforced.Tecture\Testing\Reinforced.Tecture.Testing\Data\CSharpTestData.cs:line 114
```

description == k.Description: true
hash: OrmQuery_AB78B1DAADDAD273C885641045DBA4575D5FF2948319913F64C58E6FC40F215
k.Hash OrmQuery_453C31866DD6BD48D2E31F78EC2AD153828D26DAB1C5EC2AF7C2829A94A424

I did not change anything in my test, only provided generated classes
